apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    name: api
spec:
  ports:
    # the port that this service should serve on
  - port: 3001
    targetPort: 3001
  selector:
    name: api
